module.exports = [
  'configure',
  'reset-config',
  'show-commands',
  'make-class-comp',
  'make-func-comp',
  'make-func-comp-with-redux',
  'make-class-comp-with-redux',
  'make-hoc-comp',
  'make-hoc-comp-with-redux',
  'make-scss-file',
  'make-redux-middleware',
  'make-redux-reducer',
  'make-context',
];
